### ISSUE TITLE
How to install this module ?

### ISSUE THREAD

**Issue by etorona1** [0k/web_m2o_enhanced#2]
Hi,
I add the option attibute to my xml field but i always see the create edit link.
I use openERp 7.

Thanks

**Comment by njeudy** [comment]
Hello,

To install the module you have to download it and put it in your addons
folder.
Then go to openerp -> setting -> applications and install web_m2o_enhanced
like other addons (click on the red install button)

If you don't see it in the list of addons use search widget on top right
corner, or check that your addons folder is ok.

When you have installed your module, you can user spécial option on xml
viewer.

Nicolas JEUDY

Expert Technique et Fonctionnel Système d'Information
TUXSERVICES

22 rue du seminaire - 25170 Pelousey
e-mail : njeudy@tuxservices.com
mob. : +33 (0)6 28 95 36 64
http://www.tuxservices.com

2013/9/22 etorona1 notifications@github.com

**Comment by njeudy** [comment]
Think it's ok for you to install it. Feel free to reopen if not.
