### ISSUE TITLE
New feature request on m2m

### ISSUE THREAD

**Issue by youring** [0k/web_m2o_enhanced#3]
Hi Nicolas ,
Thanks for the wonderful enhancement!
Is web_m2m_enhanced on the roadmap?
In some cases for example, we need some user to only select existing partner tags, which is m2m, not creating new tags.
Is this implementable?
Thank you!

**Comment by njeudy** [comment]
Hello,

Thank for your comment,

We did not start coding web_m2m_enhanced but I will give it a try a see how many time it will take.
I think it is implementable.

**Comment by njeudy** [comment]
Hello,

I add the functionality you need.

**Comment by youring** [comment]
Awesome!
Thanks for your time. Start testing...
