### ISSUE TITLE
can_create is not defined

### ISSUE THREAD

**Issue by youring** [0k/web_m2o_enhanced#4]
When click the dropdown triangle on Partner Tags field, pop up OpenERP Client error:

```
Uncaught ReferenceError: can_create is not defined
http://10.0.1.8/web_m2o_enhanced/static/src/js/form.js:189
```

**Comment by shaumux** [comment]
Having the same problem.

**Comment by a0c** [comment]
Same here. Any solutions?
Or just disable the M2M tags?

**Comment by youring** [comment]
http://bazaar.launchpad.net/~webaddons-core-editors/web-addons/7.0/revision/10.1.1
fix: error when displaying many2many field without options defined.
Thanks!

**Comment by njeudy** [comment]
Thanks to veloutin contrib. I think I will merge this module and the same community one.
