### ISSUE TITLE
Would you help update to Version 8.0?

### ISSUE THREAD

**Issue by jerry79** [0k/web_m2o_enhanced#6]
Hello, I use this module in openerp 8.0, have error: Uncaught TypeError: Cannot call method 'split' of undefined when I clikd the m2o widget. 
7.0 is not problem.
would you have update this module to version 8.0?
thanks very much.

**Comment by njeudy** [comment]
I, I migrate it to community project:

https://www.openerp.com/apps/7.0/web_m2x_options

And for know I have no problem with it in V8. I will test it with last revision ... You use trunk to test ?

**Comment by njeudy** [comment]
Ok I try it and can reproduce the bug. I will update web_m2x_options for latest v8

**Comment by jerry79** [comment]
thanks very much!

**Comment by njeudy** [comment]
Ok this module migrate to https://github.com/0k/web_m2x_options to be in correct state with community modules.

This new module has odoo/8.0 branch that works with v8.0 !

Thanks for bug report.
